# Generated by Django 4.0.1 on 2022-09-22 13:55

import core.models
import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('followers', models.IntegerField(default=0)),
                ('follow_fee', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(10)])),
                ('timezone', models.CharField(default='GMT+01:00', max_length=100)),
                ('biodescription', models.CharField(blank=True, default='Hey there!', max_length=4000)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default/default.png', max_length=255, null=True, upload_to=core.models.get_profle_image_filepath, validators=[core.validators.image_size])),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=10000)),
                ('auth_token', models.CharField(default='', max_length=100)),
                ('password_auth', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('ban', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='', max_length=30)),
                ('viewable_to', models.CharField(default='Everyone', max_length=15)),
                ('sec_description', models.CharField(blank=True, default='', max_length=10000, verbose_name='Section Description:')),
                ('section_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subsections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_serial', models.IntegerField(default=0)),
                ('subsection_add_date', models.CharField(blank=True, default='', max_length=100, verbose_name='Date added')),
                ('subsection_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sections')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_hash', models.CharField(default='', editable=False, max_length=10000)),
                ('post_time', models.CharField(default='', max_length=1000)),
                ('post_text', models.CharField(default='', max_length=100000)),
                ('post_image', models.ImageField(blank=True, max_length=100000, null=True, upload_to=core.models.get_post_image_filepath, validators=[core.validators.image_size])),
                ('post_video', models.FileField(blank=True, null=True, upload_to=core.models.get_post_video_filepath, validators=[core.validators.file_size])),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subsections')),
            ],
        ),
    ]
