# Generated by Django 4.0.1 on 2022-09-22 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_followerslist_alfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerslist',
            name='alfollowers',
            field=models.ManyToManyField(blank=True, related_name='allfollowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
