# Generated by Django 4.0.1 on 2022-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_followerslist_alfollowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerslist',
            name='alfollowers',
        ),
        migrations.AddField(
            model_name='followerslist',
            name='followers',
            field=models.CharField(default='', editable=False, max_length=10000),
        ),
    ]
