# Generated by Django 4.0.1 on 2022-09-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_followerslist_alfollowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerslist',
            name='followers',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
