# Generated by Django 4.0.1 on 2022-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followerslist_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerslist',
            name='following',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
