# Generated by Django 4.0.1 on 2022-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_followerslist_following_followinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
