# Generated by Django 4.0.1 on 2022-09-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accounts_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default=None, max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(default=None, max_length=100)),
                ('thread_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatfather')),
            ],
        ),
    ]
