# Generated by Django 4.0.1 on 2022-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatfather_chatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
