# Generated by Django 4.0.1 on 2022-09-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_chatmodel_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerslist',
            old_name='followers',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='followinglist',
            old_name='following',
            new_name='email',
        ),
    ]
