# Generated by Django 4.0.1 on 2022-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_followers_followerslist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_text',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
