# Generated by Django 4.0.1 on 2022-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_posts_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerslist',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
