# Generated by Django 4.0.1 on 2022-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_followerslist_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerslist',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
