# Generated by Django 4.0.1 on 2022-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_followerslist_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerslist',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='followinglist',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
