# Generated by Django 4.0.1 on 2022-10-28 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_followerslist_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='follow_fee',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
