# Generated by Django 4.0.1 on 2022-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_accounts_follow_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
