# Generated by Django 4.0.1 on 2022-11-05 12:05

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_accounts_earnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('notification_image', models.ImageField(blank=True, default='default/defaultnotifications.png', max_length=255, null=True, upload_to=core.models.get_notification_image_filepath)),
                ('notification_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
