# Generated by Django 4.0.1 on 2022-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
