# Generated by Django 4.0.1 on 2022-11-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notifications_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='R45S3L0FCVYX31FR5B0O', max_length=10000),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='5D1Y85Z858PWK47Y4BJX', max_length=10000),
        ),
    ]
