# Generated by Django 4.0.1 on 2022-11-05 12:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_chatmodel_message_id_notifications_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='4V5N4FTXRVJZJGMJRQMW7B09LELT5XAEB949BKR0B46KUGFMWC', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='2TP6K6LVQ88JSSQT9N9KOJ09SP3XXJICAO1KP9SBOK5SH9PP4L', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_image',
            field=models.ImageField(default='default/defaultnotifications.png', max_length=255, upload_to=core.models.get_notification_image_filepath),
        ),
    ]
