# Generated by Django 4.0.1 on 2022-11-05 12:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_chatmodel_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='7N8ANHFZ0MW1K5N7E48PGE1DEV88LPG2S8SWJ5DLOAT0OQ26V5', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='61C6D90WQ2CMZ46XTBOR4P5MJX005MZG4XGQXO55Q4IJYO0YT0', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_image',
            field=models.ImageField(blank=True, default='default/defaultnotifications.png', max_length=255, null=True, upload_to=core.models.get_notification_image_filepath),
        ),
    ]
