# Generated by Django 4.0.1 on 2022-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chatmodel_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='N07GWKR7BWF23I9JY1351C3K4KNZ4MPI0ZVX5VY57FS45A2SEE', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_date',
            field=models.CharField(default='November 05, 2022', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='21M9EWD3PIJKHKAPGG4FSCWYSQMPNJRC4BMKCXFX0726XLB3KW', max_length=10000),
        ),
    ]
