# Generated by Django 4.0.1 on 2022-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_chatmodel_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_sectionname_case',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('follow_key', 'follow'), ('posted_key', 'posted'), ('message_key', 'message'), ('website_key', 'website')], default='website_key', max_length=100),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_username_case',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='GEGVKQU7FPEGXS7S8WO9RAWHBSFQR5WX98JBR7AQNYANAATYZD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='8322W0KFLGXITHS5FL3WZOTSU24NC1J52SQFT9TFO0SMPEAQ1B', max_length=10000),
        ),
    ]
