# Generated by Django 4.0.1 on 2022-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notifications_notification_sectionname_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message_id',
            field=models.CharField(default='ICWM8RM2U3UY6H1E4MNJDNO4SZDYCE3NCBV9GXPN2TXY4TRLIK', max_length=10000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_id',
            field=models.CharField(default='E4WX6L9EBMW42RBFCCOEBPGZ54WZ0Z3O6UVOQJIIQT0YMB9WPR', max_length=10000),
        ),
    ]
